### ISSUE TITLE
No precompiled library

### ISSUE THREAD

**Issue by mai1015** [jocelyn/docker_eiffeldev#2]
When trying to compile a program with a precompiled library, it failed with the message.
```
The project needs to use a precompiled library, which has not been compiled.
(precompiled library: "/root/.es/eiffel_user_files/19.05/precomp/spec/linux-x86-64/base-scoop-safe.ecf")
Should the precompile be built? [y|n] y
Could not generate needed precompiled library.
```

**Comment by phgachoud** [comment]
One option is to remove the precompiled library from your ecf file
![image](https://user-images.githubusercontent.com/11555852/81095572-36642d80-8ed3-11ea-8b38-8cbb2c78a608.png)


 or into your configuration with Wizard 
![image](https://user-images.githubusercontent.com/11555852/81095450-04eb6200-8ed3-11ea-9396-6f3fc5da6679.png)
