### ISSUE TITLE
Should the precompile be built? [y|n]

### ISSUE THREAD

**Issue by yegor256** [jocelyn/docker_eiffeldev#3]
I have something similar to this bug: https://github.com/eiffel-docker/eiffel/issues/2

But my story is different: I'm trying to run `ec` from command line:

```
$ ec application.e -precompile
Should the precompile be built? [y|n] The project needs to use a precompiled library, which has not been compiled.
(precompiled library: "/home/runner/.es/eiffel_user_files/19.05/precomp/spec/unix/base-scoop-safe.ecf")
```

How do I suppress this question and just answer 'y' or 'n'?

**Comment by jocelyn** [comment]
Your command is not valid   "-precompile"  is to build a "precompile library".
You can try to use "ec application.e -batch"  to avoid interactive mode.

**Comment by yegor256** [comment]
@jocelyn now it just prints this:

```
$ ec application.e -batch
Precompile will automatically be built
because of the -stop/-batch option.
Could not generate needed precompiled library.
```

What should I do?

**Comment by jocelyn** [comment]
We need more information, how are you using this docker container ?

**Comment by yegor256** [comment]
@jocelyn I'm not. I just did this (on clean Ubuntu 20.04):

```
sudo add-apt-repository ppa:eiffelstudio-team/ppa 
sudo apt-get -y update 
sudo apt-get install -y eiffelstudio
```

and then this:

```
ec application.e -batch
```

But it seems you may know the answer and help me. Please :)

**Comment by jocelyn** [comment]
This github project is really related to the docker container for Eiffel. 
So this is not the best place to ask for Eiffel related question (but not the worst neither).

I would suggest to use https://groups.google.com/g/eiffel-users

However, you should check that ISE_PLATFORM is set to "linux-x86-64" 
then, to see why the "precompile" step may have an issue :

ec -config $ISE_EIFFEL/precomp/spec/linux-x86-64/base-scoop-safe.ecf -precompile -c_compile

Alternative, when you call "ec application.e", it should also generate an "application.ecf" , edit this file, and remove the line with "precompile" 
then "ec -config application.ecf -c_compile"
